 export const chargers = [
    {
      id: 16,
      name: "Charger 1",
      withBg: "/img2/ch1.jpeg",
      description: "Fast-charging USB-C wall adapter.",
      price: 19.99,
      category: "Charger",
      rating: 4.6,
    },
    {
      id: 17,
      name: "Charger 2",
      withBg: "/img2/ch2.jpeg",
      description: "Compact wireless charger for phones.",
      price: 24.99,
      category: "Charger",
      rating: 4.3,
    },
    {
      id: 18,
      name: "Charger 3",
      withBg: "/img2/ch3.jpeg",
      description: "Universal charger compatible with multiple devices.",
      price: 29.99,
      category: "Charger",
      rating: 4.2,
    },
    {
      id: 19,
      name: "Charger 4",
      withBg: "/img2/ch4.jpeg",
      description: "Multi-port charging station for all devices.",
      price: 34.99,
      category: "Charger",
      rating: 4.5,
    },
    {
      id: 20,
      name: "Charger 5",
      withBg: "/img2/ch5.jpeg",
      description: "High-capacity power bank for long use.",
      price: 39.99,
      category: "Charger",
      rating: 4.6,
    },
    {
      id: 15,
      name: "Charger 6",
      withBg: "/img2/ch6.jpeg",
      description: "Portable solar-powered charger.",
      price: 49.99,
      category: "Charger",
      rating: 4.7,
    },
    {
      id: 26,
      name: "Charger 7",
      withBg: "/img2/ch7.jpeg",
      description: "Smart charger with auto shut-off technology.",
      price: 27.99,
      category: "Charger",
      rating: 4.3,
    },
  ];